version: "3.9"

services:
  api:
    container_name: api
    build: .
    ports:
      - $PORT:$PORT #local : docker
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    command: bash -c "yarn typeorm migration:run -d src/data-source && yarn dev"
    volumes:
      - .:/app

  db:
    container_name: db
    image: postgres:latest
    ports:
      - $PGPORT:$PGPORT #local : Docker
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
   

